### ISSUE TITLE
Board not printing pawns

### ISSUE THREAD

**Issue by milovangudelj** [milovangudelj/scacchiera#35]
When initialising a `Board` object using this fen string `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR` and printing it out I expect the output to look like this:
```sh
8 TCADRACT
7 PPPPPPPP
6         
5         
4         
3         
2 pppppppp
1 tcadract

  ABCDEFGH
```

instead I only get this:
```sh
8 TCADRACT
7         
6         
5         
4         
3         
2         
1 tcadract

  ABCDEFGH
```

Is this a bug in `Board`, `Pawn` or `Piece`?

**Comment by Aehronburn** [comment]
Pawn does not exist yet

**Comment by milovangudelj** [comment]
It has been added in #25. You need to include it in `Board.h`, add a 
```cxx
using Chess::Pawn;
```
statement to `board.cpp` and complete the switch statement in `make_piece()` where you placed the TODO
```cxx
std::shared_ptr<Piece> make_piece(Coordinate coordinate, Color color, PieceType type) {
   switch (type) {
      // other cases...
      case PieceType::rook :
         return std::make_shared<Rook>(coordinate, color, type);
         break;
      //TODO Pawn
   }
   return nullptr;
}
```
