### ISSUE TITLE
Castling fails both with tower and king

### ISSUE THREAD

**Issue by milovangudelj** [milovangudelj/scacchiera#41]
Castling fails every time and it would be more intuitive if to do the move you had to place one piece over the other instead of moving them by x places to the left or right.

**Comment by Aehronburn** [comment]
Manca la nuova implementazione di rook, ho provato a fare dei test con king su rook e va bene

**Comment by milovangudelj** [comment]
Oki, allora ti tolgo dagli assegnati e facciamo il merge quando @JiNT1 avrà corretto l'arrocco di `Rook`.
