### ISSUE TITLE
Checkmate fails if aggressor is 'eatable'

### ISSUE THREAD

**Issue by milovangudelj** [milovangudelj/scacchiera#42]
Checkmate does not occur when the piece that is creating it is in a position where it can be eaten by the other player.

An example case looks like this:
```sh
8  T  C  A  D  R  A  C  T 
7  P  P  P  P  P  P  P  P 
6           c             
5                         
4                         
3                         
2  p  p  p  p  p  p  p  p 
1  t     a  d  r  a  c  t 

   A  B  C  D  E  F  G  H 
```
This should cause checkmate, but it doesn't since the knight is 'eatable' by the other player's knight

**Comment by Aehronburn** [comment]
per il momento credo sia perchè il nero ha modo usando i pedoni di catturare il cavallo e sventare lo scacco
